export const operationalIndexStatements = [
  "CREATE INDEX idx_incidents_tenant_status_updated ON incidents(tenant_id, status, updated_at DESC)",
  "CREATE INDEX idx_incidents_tenant_subject_updated ON incidents(tenant_id, subject_id, updated_at DESC)",
  "CREATE INDEX idx_alerts_tenant_incident_occurred ON alerts(tenant_id, incident_id, occurred_at)",
  "CREATE INDEX idx_evidence_incident_observed ON evidence_items(tenant_id, incident_id, observed_at, id)",
  "CREATE INDEX idx_evidence_incident_source ON evidence_items(tenant_id, incident_id, source)",
  "CREATE INDEX idx_workflow_incident_started ON workflow_runs(tenant_id, incident_id, started_at DESC)",
  "CREATE INDEX idx_plans_incident_created ON containment_plans(tenant_id, incident_id, created_at DESC)",
  "CREATE INDEX idx_actions_incident_status ON containment_actions(tenant_id, incident_id, status)",
  "CREATE INDEX idx_approvals_incident_requested ON approvals(tenant_id, incident_id, requested_at DESC)",
  "CREATE INDEX idx_timeline_tenant_incident_sequence ON timeline_events(tenant_id, incident_id, sequence)",
  "CREATE INDEX idx_devices_subject_authorized ON authorized_devices(tenant_id, subject_id, authorized_at DESC)",
  "CREATE INDEX idx_snapshots_subject_captured ON identity_snapshots(tenant_id, subject_id, captured_at DESC)",
  "CREATE INDEX idx_deliveries_pending ON provider_deliveries(status, next_attempt_at)",
  "CREATE INDEX idx_outbox_pending ON outbox_events(published_at, available_at, occurred_at)",
  "CREATE INDEX idx_outbox_incident ON outbox_events(tenant_id, incident_id, occurred_at)",
  "CREATE INDEX idx_dead_letters_pending ON dead_letter_events(resolved_at, created_at)",
  "CREATE INDEX idx_dead_letters_incident ON dead_letter_events(tenant_id, incident_id, created_at)",
] as const;
