export const runbookCatalogStatements = [
  `CREATE TABLE runbook_versions (
    runbook_id TEXT NOT NULL CHECK(runbook_id GLOB 'RB-IDENTITY-00[1-3]'),
    version TEXT NOT NULL CHECK(version GLOB '[0-9]*.[0-9]*.[0-9]*'),
    owner TEXT NOT NULL CHECK(owner = 'security'),
    declared_status TEXT NOT NULL CHECK(declared_status IN ('active','inactive')),
    source_path TEXT NOT NULL CHECK(source_path GLOB 'src/mastra/runbooks/*.md'),
    source_hash TEXT NOT NULL CHECK(length(source_hash) = 64 AND source_hash NOT GLOB '*[^0-9a-f]*'),
    parsed_hash TEXT NOT NULL CHECK(length(parsed_hash) = 64 AND parsed_hash NOT GLOB '*[^0-9a-f]*'),
    schema_version INTEGER NOT NULL CHECK(schema_version = 1),
    chunking_algorithm_version INTEGER NOT NULL CHECK(chunking_algorithm_version = 1),
    embedding_provider TEXT NOT NULL CHECK(embedding_provider = 'fastembed'),
    embedding_model TEXT NOT NULL CHECK(embedding_model = 'bge-small-en-v1.5'),
    embedding_dimension INTEGER NOT NULL CHECK(embedding_dimension = 384),
    allowed_actions_json TEXT NOT NULL CHECK(json_valid(allowed_actions_json)),
    created_at TEXT NOT NULL CHECK(created_at GLOB '????-??-??T??:??:??.???Z'),
    PRIMARY KEY(runbook_id, version)
  ) STRICT`,
  `CREATE TABLE runbook_generations (
    generation_id TEXT PRIMARY KEY CHECK(length(trim(generation_id)) BETWEEN 1 AND 128),
    runbook_id TEXT NOT NULL,
    version TEXT NOT NULL,
    incident_kind TEXT NOT NULL CHECK(incident_kind IN ('unauthorized_privilege_change','disallowed_country_login','unknown_device_login')),
    index_name TEXT NOT NULL UNIQUE CHECK(index_name GLOB 'rb_[a-z0-9_]*'),
    state TEXT NOT NULL CHECK(state IN ('staged','active','retired','failed')),
    chunk_count INTEGER NOT NULL CHECK(chunk_count >= 0),
    aggregate_hash TEXT NOT NULL CHECK(length(aggregate_hash) = 64 AND aggregate_hash NOT GLOB '*[^0-9a-f]*'),
    created_at TEXT NOT NULL CHECK(created_at GLOB '????-??-??T??:??:??.???Z'),
    activated_at TEXT CHECK(activated_at IS NULL OR activated_at GLOB '????-??-??T??:??:??.???Z'),
    retired_at TEXT CHECK(retired_at IS NULL OR retired_at GLOB '????-??-??T??:??:??.???Z'),
    error_code TEXT CHECK(error_code IS NULL OR length(error_code) BETWEEN 1 AND 128),
    UNIQUE(generation_id, runbook_id, version, incident_kind),
    FOREIGN KEY(runbook_id, version) REFERENCES runbook_versions(runbook_id, version) ON DELETE RESTRICT
  ) STRICT`,
  `CREATE TABLE runbook_chunks (
    generation_id TEXT NOT NULL,
    chunk_id TEXT NOT NULL CHECK(chunk_id GLOB 'rch_[0-9a-f]*' AND length(chunk_id) = 68),
    vector_id TEXT NOT NULL,
    runbook_id TEXT NOT NULL,
    version TEXT NOT NULL,
    incident_kind TEXT NOT NULL,
    section_key TEXT NOT NULL,
    section_ordinal INTEGER NOT NULL CHECK(section_ordinal BETWEEN 1 AND 9),
    chunk_ordinal INTEGER NOT NULL CHECK(chunk_ordinal >= 0),
    text TEXT NOT NULL CHECK(length(text) BETWEEN 1 AND 1200),
    content_hash TEXT NOT NULL CHECK(length(content_hash) = 64 AND content_hash NOT GLOB '*[^0-9a-f]*'),
    metadata_hash TEXT NOT NULL CHECK(length(metadata_hash) = 64 AND metadata_hash NOT GLOB '*[^0-9a-f]*'),
    metadata_json TEXT NOT NULL CHECK(json_valid(metadata_json)),
    indexed_at TEXT CHECK(indexed_at IS NULL OR indexed_at GLOB '????-??-??T??:??:??.???Z'),
    PRIMARY KEY(generation_id, chunk_id),
    UNIQUE(generation_id, vector_id),
    UNIQUE(generation_id, chunk_id, vector_id),
    UNIQUE(generation_id, section_ordinal, chunk_ordinal),
    FOREIGN KEY(generation_id, runbook_id, version, incident_kind)
      REFERENCES runbook_generations(generation_id, runbook_id, version, incident_kind) ON DELETE RESTRICT
  ) STRICT`,
  `CREATE INDEX idx_runbook_generations_kind_state ON runbook_generations(incident_kind, state)`,
  `CREATE INDEX idx_runbook_generations_version ON runbook_generations(runbook_id, version)`,
  `CREATE INDEX idx_runbook_chunks_order ON runbook_chunks(generation_id, section_ordinal, chunk_ordinal)`,
  `CREATE INDEX idx_runbook_chunks_hash ON runbook_chunks(generation_id, content_hash, metadata_hash)`,
] as const;
